development:
  adapter: postgresql
  encoding: unicode
  database: temporal-tables-demo
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: temporal-tables-demo-test
  username: postgres
  password: postgres
